### PR TITLE
Add paging support for resistance calendar

### PR DESCRIPTION
**Pull request by john**

### CODE REVIEW

**Comment by bnd5k** [comment]
@AaronSofaer  Can you fill this issue about a bit more?  Is this an API or a website?  Can you post a link to where they're storing CTAs currently?

**Comment by john** [comment]
At the least it's an API:
https://resistance-calendar.herokuapp.com/v1/events?page=1

I too wondered where all this is data is currently being used--as well as where it's coming from.

**Comment by bnd5k** [comment]
Thanks for the PR. :)

When I run the rake task locally, I get 237 scrape fails (luckily it looks like they're all the same error).  Can we get them squared away before we move this to staging and then prod?  I'd prefer not to create ScrapeFail records if we know ahead of time that we can avoid it.

So far all the errors I'm seeing are instances where Resistance Calendar is more permissive than the CTAA when it comes to a location.  This is the error: "requires locality and region or postal_code.  

@AaronSofaer can correct me if I'm wrong, but we probably want to show anything that's already being shown by Resistence Calendar.  Can I can I ask you to make a small PR in the API repo that relaxes the Location validations?

**Comment by john** [comment]
Thank @bnd5k, had missed that, will fix (hopefully tomorrow). I agree, makes sense that we be able to display anything Resistance Calendar can.

**Comment by bnd5k** [comment]
@john I added a commit to your branch.

I relaxed the like we talked about above, but even after that the rake task encountered 2 errors.

It turns out that Resistance Calendar occasionally includes events in Australia.  We're only doing US CTAs at this point.

**Pull request merged**
