### PR TITLE
Feature/update ctaa gem

### PR DESCRIPTION
**Pull request by bnd5k**
This PR:

- Updates CTAA gem
- Updates the scraper so they use the new, simpler interfact for the CTAA gem
- Fixes the emily's list scraper to avoid some errors I saw while adding this feature.

### CODE REVIEW

**Comment by greysteil** [comment]
Would you be up for automatically creating dependency update PRs? Obviously wouldn't be able to fix all the breaking changes you've taken care of here, but I wrote [Dependabot](https://dependabot.com) at my previous company to create a PR whenever a new dependency version is released. It's totally free for open source, and was a real timesaver for us.

**Comment by bnd5k** [comment]
Given how small the team is and that we pretty much know when this repo will need a new version of CTAA gem, I don't see a lot of need for Dependabot.

**Comment by greysteil** [comment]
Fair enough - you know you're not on the latest versions of rails, puma or rspec, though? 😉

**Comment by bnd5k** [comment]
We're on stable versions of all our dependencies.  That's more important than having the absolutely latest version.

I can't imagine the value of blindly whipping up PR's any time a dependency changes.  It'd focus the team on dependency management rather than shipping features.  That's not the prioritization we want.

I'd be happy to talk more about depdendabot after you help us close a few of our outstanding issues. https://github.com/Ragtagteam/cta-aggregator/issues

**Comment by greysteil** [comment]
Ah, sorry man, was honestly just trying to help :octocat:

**Comment by AaronSofaer** [comment]
No need to apologize, @greysteil . It's a good point, and once we've launched the 1.0 version of our fully operational [s]battle station[/s] aggregator and API, it's a conversation we should have. (This would be sometime in 2018.) If you'd like, please create an Issue about it.

**Review by AaronSofaer — APPROVED** [review]
LGTM!

**Pull request merged**
